# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParallelCoordinates
                                 A QGIS plugin
 Provides a graphical way to filter features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-25
        copyright            : (C) 2020 by Fidel Serrano Candela/LANCIS UNAM
        email                : serranoycandela@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParallelCoordinates class from file ParallelCoordinates.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .parallel_coordinates import ParallelCoordinates
    return ParallelCoordinates(iface)
